apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: goon-api-cert
  namespace: istio-system
spec:
  secretName: goon-api-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.goonplanet.co.kr
  dnsNames:
  - api.goonplanet.co.kr

