apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: istio-system
spec:
  secretName: test-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: test.rolancia.com
  dnsNames:
  - test.rolancia.com

