apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ingress
  namespace: default
spec:
  hosts: 
  - '*'
  gateways:
  - gateway
  http:
  - route:
    - destination: 
        host: echo

