apiVersion: apps/v1
kind: Deployment
metadata:
  name: goon-api
  namespace: goonplanet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goon-api
      tier: app
      version: v1
  template:
    metadata:
      labels:
        app: goon-api
        tier: app
        version: v1
      annotations:
        release: prometheus
    spec:
      containers:
        - name: goon-api
          image: rolancia1/goon-api
          env:
          - name: PORT
            value: "3000"
          - name: CORS_ORIGIN
            value: "https://goonplanet.co.kr"
          - name: FIREBASE_KEY
            value: "/etc/secret/goonplanet-firebase-admin.json"
          - name: MONGO_URI
            value: ""

---
apiVersion: v1
kind: Service
metadata:
  name: goon-api
  namespace: goonplanet
spec:
  type: ClusterIP
  selector:
    app: goon-api
    tier: app
    version: v1
  ports:
    - protocol: TCP
      port: 3000

