apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cb-cert
  namespace: istio-system
spec:
  secretName: cb-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: cb.rolancia.com
  dnsNames:
  - cb.rolancia.com

