apiVersion: v1
kind: Secret
metadata:
  name: cb-secret
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg== # Administrator
  password: cGFzc3dvcmQ=         # password
---
apiVersion: v1
kind: Secret
metadata:
  name: cb-metrics-token
type: Opaque
stringData:
  token: "asd"
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: default
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb
spec:
  image: couchbase/server:7.1.1
  autoResourceAllocation:
    cpuLimits: 1
    cpuRequests:  "500m"
    enabled: true
    overheadPercent: 40
  security:
    adminSecret: cb-secret
  buckets:
    managed: true
  servers:
  - size: 2
    name: cb-data
    services:
    - data
    volumeMounts:
      default: couchbase
  - size: 1
    name: cb-index
    autoscaleEnabled: true
    services:
    - index
    volumeMounts:
      default: couchbase-sm
  - size: 1
    name: cb-lookup
    autoscaleEnabled: true
    services:
    - query
    - search
    volumeMounts:
      default: couchbase-sm
  - size: 1
    name: cb-etc
    autoscaleEnabled: true
    services:
    - eventing
    - analytics
    volumeMounts:
      default: couchbase-sm
  volumeClaimTemplates:
  - metadata:
      name: couchbase
    spec:
      resources:
        requests:
          storage: 40Gi
  - metadata:
      name: couchbase-sm
    spec:
      resources:
        requests:
          storage: 2Gi
  networking:
    exposeAdminConsole: true
    exposedFeatures: 
    - client
    dns:
      domain: cb.rolancia.com
  monitoring:
    prometheus:
      enabled: true
      image: couchbase/exporter:1.0.6
      authorizationSecret: cb-metrics-token


