apiVersion: v1 
kind: Secret
metadata:
  name: cb-user-secret
type: Opaque
data:
  password: cGFzc3dk


---
apiVersion: couchbase.com/v2
kind: CouchbaseUser
metadata:
  name: cb-user
spec:
  fullName: default-user
  authDomain: local
  authSecret: cb-user-secret


---
apiVersion: couchbase.com/v2
kind: CouchbaseGroup
metadata:
  name: cb-group
spec:
  roles:
  - name: replication_admin
  - name: data_reader
    bucket: default

---
apiVersion: couchbase.com/v2
kind: CouchbaseRoleBinding
metadata:
  name: cb-group-binding
spec:
  subjects:
  - kind: CouchbaseUser
    name: cb-user
  roleRef:
    kind: CouchbaseGroup
    name: cb-group
