apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: istio-system
spec:
  secretName: grafana-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: grafana.rolancia.com
  dnsNames:
  - grafana.rolancia.com

