apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: owncloud-cert
  namespace: istio-system
spec:
  secretName: owncloud-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: owncloud.rolancia.com
  dnsNames:
  - owncloud.rolancia.com


